# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gbConnection = QtWidgets.QGroupBox(self.centralwidget)
        self.gbConnection.setObjectName("gbConnection")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbConnection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblSlackToken = QtWidgets.QLabel(self.gbConnection)
        self.lblSlackToken.setObjectName("lblSlackToken")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblSlackToken)
        self.leSlackToken = QtWidgets.QLineEdit(self.gbConnection)
        self.leSlackToken.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leSlackToken.setObjectName("leSlackToken")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leSlackToken)
        self.lblStatus = QtWidgets.QLabel(self.gbConnection)
        self.lblStatus.setObjectName("lblStatus")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblStatus)
        self.lblConnectionStatus = QtWidgets.QLabel(self.gbConnection)
        self.lblConnectionStatus.setObjectName("lblConnectionStatus")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblConnectionStatus)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.pbConnect = QtWidgets.QPushButton(self.gbConnection)
        self.pbConnect.setObjectName("pbConnect")
        self.gridLayout_2.addWidget(self.pbConnect, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.gbConnection, 0, 0, 1, 1)
        self.gbChannels = QtWidgets.QGroupBox(self.centralwidget)
        self.gbChannels.setObjectName("gbChannels")
        self.gridLayout = QtWidgets.QGridLayout(self.gbChannels)
        self.gridLayout.setObjectName("gridLayout")
        self.lvChannels = QtWidgets.QListView(self.gbChannels)
        self.lvChannels.setObjectName("lvChannels")
        self.gridLayout.addWidget(self.lvChannels, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.gbChannels, 0, 1, 2, 1)
        self.gbMessage = QtWidgets.QGroupBox(self.centralwidget)
        self.gbMessage.setObjectName("gbMessage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbMessage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pbSend = QtWidgets.QPushButton(self.gbMessage)
        self.pbSend.setObjectName("pbSend")
        self.gridLayout_3.addWidget(self.pbSend, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.teMsg = QtWidgets.QTextEdit(self.gbMessage)
        self.teMsg.setObjectName("teMsg")
        self.gridLayout_3.addWidget(self.teMsg, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.gbMessage, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Slack Maestro"))
        self.gbConnection.setTitle(_translate("MainWindow", "Connection"))
        self.lblSlackToken.setText(_translate("MainWindow", "Slack token"))
        self.leSlackToken.setText(_translate("MainWindow", "xoxb-2008514871233-1992851393701-L1KVcgB02FaIAcoOsLVp1RFw"))
        self.lblStatus.setText(_translate("MainWindow", "Status"))
        self.lblConnectionStatus.setText(_translate("MainWindow", "Not connected"))
        self.pbConnect.setText(_translate("MainWindow", "Connect"))
        self.gbChannels.setTitle(_translate("MainWindow", "Channels"))
        self.gbMessage.setTitle(_translate("MainWindow", "Message"))
        self.pbSend.setText(_translate("MainWindow", "Send"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
