# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 829)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pbGenerateRandom = QtWidgets.QPushButton(self.centralwidget)
        self.pbGenerateRandom.setObjectName("pbGenerateRandom")
        self.gridLayout.addWidget(self.pbGenerateRandom, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.leSeed = QtWidgets.QLineEdit(self.centralwidget)
        self.leSeed.setObjectName("leSeed")
        self.gridLayout.addWidget(self.leSeed, 0, 1, 1, 1)
        self.lblImage = QtWidgets.QLabel(self.centralwidget)
        self.lblImage.setText("")
        self.lblImage.setPixmap(QtGui.QPixmap(":/sample"))
        self.lblImage.setScaledContents(True)
        self.lblImage.setObjectName("lblImage")
        self.gridLayout.addWidget(self.lblImage, 1, 0, 1, 7)
        self.lblSeed = QtWidgets.QLabel(self.centralwidget)
        self.lblSeed.setObjectName("lblSeed")
        self.gridLayout.addWidget(self.lblSeed, 0, 0, 1, 1)
        self.pbTheEnd = QtWidgets.QPushButton(self.centralwidget)
        self.pbTheEnd.setObjectName("pbTheEnd")
        self.gridLayout.addWidget(self.pbTheEnd, 0, 5, 1, 1)
        self.pbGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.pbGenerate.setObjectName("pbGenerate")
        self.gridLayout.addWidget(self.pbGenerate, 0, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbGenerateRandom.setText(_translate("MainWindow", "Generate Random"))
        self.leSeed.setText(_translate("MainWindow", "265"))
        self.lblSeed.setText(_translate("MainWindow", "Seed"))
        self.pbTheEnd.setText(_translate("MainWindow", "The End"))
        self.pbGenerate.setText(_translate("MainWindow", "Generate"))
import resources_rc
